using System;
using System.ComponentModel;

namespace IntegrationExcelImporter.Common.Utility
{
    [TypeConverter(typeof(EnumDescriptionTypeConverter))]
    public enum Option
    {
        [Description("교육종류")]
        KindOfEducation,
        [Description("교육과정명")]
        EducationName,
        [Description("교육일수")]
        EducationDay,
        [Description("교육시간")]
        EducationTime,
        [Description("교육기관")]
        EducationAgency,
        [Description("소속팀")]
        Team,
        [Description("직위")]
        Position,
        [Description("성명")]
        Name,
        [Description("수강료")]
        TuitionFee,
        [Description("출장비")]
        TravelFee,
        [Description("계")]
        SumOfFee,
        [Description("1")]
        January,
        [Description("2")]
        February,
        [Description("3")]
        March,
        [Description("4")]
        April,
        [Description("5")]
        May,
        [Description("6")]
        June,
        [Description("7")]
        July,
        [Description("8")]
        August,
        [Description("9")]
        September,
        [Description("10")]
        October,
        [Description("11")]
        November,
        [Description("12")]
        December,
        [Description("교육장소")]
        Spot,
        [Description("교육신청사유")]
        Reason,
        [Description("실무적용계획")]
        Planning
    }
}
